version: '3'
services:
  fitsync-postgres:
    image: postgres:15
    container_name: "fitsync-postgres-db"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - fitsync-postgres-db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  fitsync-postgres-db: